version: "3"

services:
  db:
    init: true
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    init: true
    container_name: front
    restart: always
    build:
      context: ./front
    image: front
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - frontend_node_modules:/app/node_modules

  back:
    init: true
    depends_on:
      - db
    container_name: back
    restart: always
    build:
      context: ./back
    image: back
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - CHAT_SOCKET_PORT=${CHAT_SOCKET_PORT}
      - USER_SOCKET_PORT=${USER_SOCKET_PORT}
      - GAME_SOCKET_PORT=${GAME_SOCKET_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${CHAT_SOCKET_PORT}:${CHAT_SOCKET_PORT}"
      - "${USER_SOCKET_PORT}:${USER_SOCKET_PORT}"
      - "${GAME_SOCKET_PORT}:${GAME_SOCKET_PORT}"
    expose:
      - "${BACKEND_PORT}"
      - "${CHAT_SOCKET_PORT}"
      - "${USER_SOCKET_PORT}"
      - "${GAME_SOCKET_PORT}"
    volumes:
      - backend_node_modules:/app/node_modules
      - public:/public

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
  public:
