version: "3"

services:
  db:
    env_file:
      - .env.prod
    ports:
      - ${DB_PORT}:${DB_PORT}

  front:
    command: sh -c "npm run build && npm run start"
    env_file:
      - .env.prod
    # volumes:
      # - ../front:/app

  back:
    command: sh -c "npm run build && npm run start:prod"

    env_file:
      - .env.prod
    # volumes:
      # - ../back:/app
